=== N16K-ed/LMGM/VScode/XML_XSD/players.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="players">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="player" maxOccurs="2">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nickname" type="dniatribute"/>             
              <xs:element name="age">
                <xs:simpleType>
                  <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="100"/>
                  </xs:restriction>                 
                </xs:simpleType>
              </xs:element>
              <xs:element name="birthday" type="xs:date" />
              <xs:element name="results">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="points" maxOccurs="unbounded" >
                      <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                          <xs:totalDigits value="5"/>                        
                          <xs:fractionDigits value="3"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>                    
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="podium" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>






<!--- Age restricition globally

  <xs:simpleType name="Agerestrictions">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="100"/>
      </xs:restriction>
  </xs:simpleType>

  and we put type="Agerestriction" in the element
   <xs:element name="age" type="Agerestriction"> -->

  <xs:complexType name="dniatribute">   
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="dni">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{8}[-][A-Z]"/>
                <!-- el rango de 0-9 repetido{8} veces-->
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>         
        </xs:extension>
      </xs:simpleContent>    
  </xs:complexType>
</xs:schema>

=== N16K-ed/LMGM/VScode/XML_XSD/players.xml
<?xml version="1.0" encoding="UTF-8"?>
<players xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="players.xsd" >
   <!-- The element player can appear two times -->
    <player podium="1">
      <!-- Define dni globally, by including an extension-->
       <nickname dni="12345678-B">hakuna_matata</nickname>
       <!-- limit the age in the interval [0-100],
      before to send the exercise, show two solutions: local and global -->
       <age>18</age>
       <birthday>1990-09-23</birthday>
       <results>
          <!-- Define the number of digits and the number of fraction digits -->
          <points>1.980</points>
          <points>23.647</points>
          <points>29.384</points>
      </results>
    </player>
    <player podium="2">
      <nickname dni="87654321-W">asdf_fdsa</nickname>
      <age>28</age>
      <birthday>1996-02-13</birthday>
      <results>
          <points>5.980</points>
          <points>13.647</points>
          <points>19.384</points>
      </results>
    </player>
</players>
